/* CVS $Id: $ */
 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from http://qudt.org/1.1/schema/qudt# 
 * @author Auto-generated by schemagen on 19 Apr 2013 23:10 
 */
public class Qudt {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://qudt.org/schema/qudt#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property abbreviation = m_model.createProperty( "http://qudt.org/schema/qudt#abbreviation" );
    
    public static final Property allowedUnitOfSystem = m_model.createProperty( "http://qudt.org/schema/qudt#allowedUnitOfSystem" );
    
    public static final Property baseDimensionEnumeration = m_model.createProperty( "http://qudt.org/schema/qudt#baseDimensionEnumeration" );
    
    public static final Property baseQuantityKindOfSystem = m_model.createProperty( "http://qudt.org/schema/qudt#baseQuantityKindOfSystem" );
    
    public static final Property baseUnitOfSystem = m_model.createProperty( "http://qudt.org/schema/qudt#baseUnitOfSystem" );
    
    public static final Property basisElement = m_model.createProperty( "http://qudt.org/schema/qudt#basisElement" );
    
    public static final Property code = m_model.createProperty( "http://qudt.org/schema/qudt#code" );
    
    public static final Property coherentDerivedUnitOfSystem = m_model.createProperty( "http://qudt.org/schema/qudt#coherentDerivedUnitOfSystem" );
    
    public static final Property coherentUnitOfSystem = m_model.createProperty( "http://qudt.org/schema/qudt#coherentUnitOfSystem" );
    
    public static final Property coherentUnitSystem = m_model.createProperty( "http://qudt.org/schema/qudt#coherentUnitSystem" );
    
    public static final Property conversionCoefficient = m_model.createProperty( "http://qudt.org/schema/qudt#conversionCoefficient" );
    
    public static final Property conversionMultiplier = m_model.createProperty( "http://qudt.org/schema/qudt#conversionMultiplier" );
    
    public static final Property conversionOffset = m_model.createProperty( "http://qudt.org/schema/qudt#conversionOffset" );
    
    public static final Property currencyExponent = m_model.createProperty( "http://qudt.org/schema/qudt#currencyExponent" );
    
    public static final Property default_ = m_model.createProperty( "http://qudt.org/schema/qudt#default" );
    
    public static final Property definedUnitOfSystem = m_model.createProperty( "http://qudt.org/schema/qudt#definedUnitOfSystem" );
    
    public static final Property derivedQuantityKindOfSystem = m_model.createProperty( "http://qudt.org/schema/qudt#derivedQuantityKindOfSystem" );
    
    public static final Property derivedUnitOfSystem = m_model.createProperty( "http://qudt.org/schema/qudt#derivedUnitOfSystem" );
    
    public static final Property description = m_model.createProperty( "http://qudt.org/schema/qudt#description" );
    
    public static final Property dimensionInverse = m_model.createProperty( "http://qudt.org/schema/qudt#dimensionInverse" );
    
    public static final Property element = m_model.createProperty( "http://qudt.org/schema/qudt#element" );
    
    public static final Property elementKind = m_model.createProperty( "http://qudt.org/schema/qudt#elementKind" );
    
    public static final Property exactConstant = m_model.createProperty( "http://qudt.org/schema/qudt#exactConstant" );
    
    public static final Property exactMatch = m_model.createProperty( "http://qudt.org/schema/qudt#exactMatch" );
    
    public static final Property generalization = m_model.createProperty( "http://qudt.org/schema/qudt#generalization" );
    
    public static final Property literal = m_model.createProperty( "http://qudt.org/schema/qudt#literal" );
    
    public static final Property negativeDeltaLimit = m_model.createProperty( "http://qudt.org/schema/qudt#negativeDeltaLimit" );
    
    public static final Property numericValue = m_model.createProperty( "http://qudt.org/schema/qudt#numericValue" );
    
    public static final Property order = m_model.createProperty( "http://qudt.org/schema/qudt#order" );
    
    public static final Property positiveDeltaLimit = m_model.createProperty( "http://qudt.org/schema/qudt#positiveDeltaLimit" );
    
    public static final Property prefixUnitOfSystem = m_model.createProperty( "http://qudt.org/schema/qudt#prefixUnitOfSystem" );
    
    public static final Property quantity = m_model.createProperty( "http://qudt.org/schema/qudt#quantity" );
    
    public static final Property quantityKind = m_model.createProperty( "http://qudt.org/schema/qudt#quantityKind" );
    
    public static final Property quantityKindOfSystem = m_model.createProperty( "http://qudt.org/schema/qudt#quantityKindOfSystem" );
    
    public static final Property quantityValue = m_model.createProperty( "http://qudt.org/schema/qudt#quantityValue" );
    
    public static final Property referenceThing = m_model.createProperty( "http://qudt.org/schema/qudt#referenceThing" );
    
    public static final Property referenceUnit = m_model.createProperty( "http://qudt.org/schema/qudt#referenceUnit" );
    
    public static final Property relativeStandardUncertainty = m_model.createProperty( "http://qudt.org/schema/qudt#relativeStandardUncertainty" );
    
    public static final Property specialization = m_model.createProperty( "http://qudt.org/schema/qudt#specialization" );
    
    public static final Property standardUncertainty = m_model.createProperty( "http://qudt.org/schema/qudt#standardUncertainty" );
    
    public static final Property symbol = m_model.createProperty( "http://qudt.org/schema/qudt#symbol" );
    
    public static final Property systemAllowedUnit = m_model.createProperty( "http://qudt.org/schema/qudt#systemAllowedUnit" );
    
    public static final Property systemBaseQuantityKind = m_model.createProperty( "http://qudt.org/schema/qudt#systemBaseQuantityKind" );
    
    public static final Property systemBaseUnit = m_model.createProperty( "http://qudt.org/schema/qudt#systemBaseUnit" );
    
    public static final Property systemCoherentDerivedUnit = m_model.createProperty( "http://qudt.org/schema/qudt#systemCoherentDerivedUnit" );
    
    public static final Property systemCoherentUnit = m_model.createProperty( "http://qudt.org/schema/qudt#systemCoherentUnit" );
    
    public static final Property systemDefinedUnit = m_model.createProperty( "http://qudt.org/schema/qudt#systemDefinedUnit" );
    
    public static final Property systemDerivedQuantityKind = m_model.createProperty( "http://qudt.org/schema/qudt#systemDerivedQuantityKind" );
    
    public static final Property systemDerivedUnit = m_model.createProperty( "http://qudt.org/schema/qudt#systemDerivedUnit" );
    
    public static final Property systemDimension = m_model.createProperty( "http://qudt.org/schema/qudt#systemDimension" );
    
    public static final Property systemPrefixUnit = m_model.createProperty( "http://qudt.org/schema/qudt#systemPrefixUnit" );
    
    public static final Property systemQuantityKind = m_model.createProperty( "http://qudt.org/schema/qudt#systemQuantityKind" );
    
    public static final Property systemUnit = m_model.createProperty( "http://qudt.org/schema/qudt#systemUnit" );
    
    public static final Property typePrefix = m_model.createProperty( "http://qudt.org/schema/qudt#typePrefix" );
    
    public static final Property uneceCommonCode = m_model.createProperty( "http://qudt.org/schema/qudt#uneceCommonCode" );
    
    public static final Property unit = m_model.createProperty( "http://qudt.org/schema/qudt#unit" );
    
    public static final Property unitFor = m_model.createProperty( "http://qudt.org/schema/qudt#unitFor" );
    
    public static final Property unitOfSystem = m_model.createProperty( "http://qudt.org/schema/qudt#unitOfSystem" );
    
    public static final Property unitSystem = m_model.createProperty( "http://qudt.org/schema/qudt#unitSystem" );
    
    public static final Property value = m_model.createProperty( "http://qudt.org/schema/qudt#value" );
    
    public static final Property valueQuantity = m_model.createProperty( "http://qudt.org/schema/qudt#valueQuantity" );
    
    public static final Property vectorMagnitude = m_model.createProperty( "http://qudt.org/schema/qudt#vectorMagnitude" );
    
    public static final Resource AbsorbedDoseRateUnit = m_model.createResource( "http://qudt.org/schema/qudt#AbsorbedDoseRateUnit" );
    
    public static final Resource AbsorbedDoseUnit = m_model.createResource( "http://qudt.org/schema/qudt#AbsorbedDoseUnit" );
    
    public static final Resource AccelerationUnit = m_model.createResource( "http://qudt.org/schema/qudt#AccelerationUnit" );
    
    public static final Resource ActivityUnit = m_model.createResource( "http://qudt.org/schema/qudt#ActivityUnit" );
    
    public static final Resource AmountOfSubstanceTemperatureUnit = m_model.createResource( "http://qudt.org/schema/qudt#AmountOfSubstanceTemperatureUnit" );
    
    public static final Resource AmountOfSubstanceUnit = m_model.createResource( "http://qudt.org/schema/qudt#AmountOfSubstanceUnit" );
    
    public static final Resource AngleUnit = m_model.createResource( "http://qudt.org/schema/qudt#AngleUnit" );
    
    public static final Resource AngularAccelerationUnit = m_model.createResource( "http://qudt.org/schema/qudt#AngularAccelerationUnit" );
    
    public static final Resource AngularMassUnit = m_model.createResource( "http://qudt.org/schema/qudt#AngularMassUnit" );
    
    public static final Resource AngularMomentumUnit = m_model.createResource( "http://qudt.org/schema/qudt#AngularMomentumUnit" );
    
    public static final Resource AngularVelocityUnit = m_model.createResource( "http://qudt.org/schema/qudt#AngularVelocityUnit" );
    
    public static final Resource AreaAngleUnit = m_model.createResource( "http://qudt.org/schema/qudt#AreaAngleUnit" );
    
    public static final Resource AreaTemperatureUnit = m_model.createResource( "http://qudt.org/schema/qudt#AreaTemperatureUnit" );
    
    public static final Resource AreaThermalExpansionUnit = m_model.createResource( "http://qudt.org/schema/qudt#AreaThermalExpansionUnit" );
    
    public static final Resource AreaTimeTemperatureUnit = m_model.createResource( "http://qudt.org/schema/qudt#AreaTimeTemperatureUnit" );
    
    public static final Resource AreaUnit = m_model.createResource( "http://qudt.org/schema/qudt#AreaUnit" );
    
    public static final Resource AtomicChargeUnit = m_model.createResource( "http://qudt.org/schema/qudt#AtomicChargeUnit" );
    
    public static final Resource AtomicMassUnit = m_model.createResource( "http://qudt.org/schema/qudt#AtomicMassUnit" );
    
    public static final Resource AtomicPhysicsUnit = m_model.createResource( "http://qudt.org/schema/qudt#AtomicPhysicsUnit" );
    
    public static final Resource BaseUnit = m_model.createResource( "http://qudt.org/schema/qudt#BaseUnit" );
    
    public static final Resource BendingMomentOrTorqueUnit = m_model.createResource( "http://qudt.org/schema/qudt#BendingMomentOrTorqueUnit" );
    
    public static final Resource BinaryPrefixUnit = m_model.createResource( "http://qudt.org/schema/qudt#BinaryPrefixUnit" );
    
    public static final Resource BiomedicalUnit = m_model.createResource( "http://qudt.org/schema/qudt#BiomedicalUnit" );
    
    public static final Resource CapacitanceUnit = m_model.createResource( "http://qudt.org/schema/qudt#CapacitanceUnit" );
    
    public static final Resource CatalyticActivityUnit = m_model.createResource( "http://qudt.org/schema/qudt#CatalyticActivityUnit" );
    
    public static final Resource ChemistryUnit = m_model.createResource( "http://qudt.org/schema/qudt#ChemistryUnit" );
    
    public static final Resource CoefficientOfHeatTransferUnit = m_model.createResource( "http://qudt.org/schema/qudt#CoefficientOfHeatTransferUnit" );
    
    public static final Resource CommunicationsUnit = m_model.createResource( "http://qudt.org/schema/qudt#CommunicationsUnit" );
    
    public static final Resource ComputingUnit = m_model.createResource( "http://qudt.org/schema/qudt#ComputingUnit" );
    
    public static final Resource ConcentrationUnit = m_model.createResource( "http://qudt.org/schema/qudt#ConcentrationUnit" );
    
    public static final Resource ConductanceUnit = m_model.createResource( "http://qudt.org/schema/qudt#ConductanceUnit" );
    
    public static final Resource CountingUnit = m_model.createResource( "http://qudt.org/schema/qudt#CountingUnit" );
    
    public static final Resource CurrencyUnit = m_model.createResource( "http://qudt.org/schema/qudt#CurrencyUnit" );
    
    public static final Resource CurrentPerAngleUnit = m_model.createResource( "http://qudt.org/schema/qudt#CurrentPerAngleUnit" );
    
    public static final Resource CurvatureUnit = m_model.createResource( "http://qudt.org/schema/qudt#CurvatureUnit" );
    
    public static final Resource DataRateUnit = m_model.createResource( "http://qudt.org/schema/qudt#DataRateUnit" );
    
    public static final Resource DecimalPrefixUnit = m_model.createResource( "http://qudt.org/schema/qudt#DecimalPrefixUnit" );
    
    public static final Resource DerivedUnit = m_model.createResource( "http://qudt.org/schema/qudt#DerivedUnit" );
    
    public static final Resource DimensionlessUnit = m_model.createResource( "http://qudt.org/schema/qudt#DimensionlessUnit" );
    
    public static final Resource DoseEquivalentUnit = m_model.createResource( "http://qudt.org/schema/qudt#DoseEquivalentUnit" );
    
    public static final Resource DynamicViscosityUnit = m_model.createResource( "http://qudt.org/schema/qudt#DynamicViscosityUnit" );
    
    public static final Resource ElectricChargeAreaDensityUnit = m_model.createResource( "http://qudt.org/schema/qudt#ElectricChargeAreaDensityUnit" );
    
    public static final Resource ElectricChargeDensityUnit = m_model.createResource( "http://qudt.org/schema/qudt#ElectricChargeDensityUnit" );
    
    public static final Resource ElectricChargeLineDensityUnit = m_model.createResource( "http://qudt.org/schema/qudt#ElectricChargeLineDensityUnit" );
    
    public static final Resource ElectricChargePerAmountOfSubstanceUnit = m_model.createResource( "http://qudt.org/schema/qudt#ElectricChargePerAmountOfSubstanceUnit" );
    
    public static final Resource ElectricChargeUnit = m_model.createResource( "http://qudt.org/schema/qudt#ElectricChargeUnit" );
    
    public static final Resource ElectricChargeVolumeDensityUnit = m_model.createResource( "http://qudt.org/schema/qudt#ElectricChargeVolumeDensityUnit" );
    
    public static final Resource ElectricCurrentDensityUnit = m_model.createResource( "http://qudt.org/schema/qudt#ElectricCurrentDensityUnit" );
    
    public static final Resource ElectricCurrentUnit = m_model.createResource( "http://qudt.org/schema/qudt#ElectricCurrentUnit" );
    
    public static final Resource ElectricDipoleMomentUnit = m_model.createResource( "http://qudt.org/schema/qudt#ElectricDipoleMomentUnit" );
    
    public static final Resource ElectricFieldStrengthUnit = m_model.createResource( "http://qudt.org/schema/qudt#ElectricFieldStrengthUnit" );
    
    public static final Resource ElectricFluxDensityUnit = m_model.createResource( "http://qudt.org/schema/qudt#ElectricFluxDensityUnit" );
    
    public static final Resource ElectricFluxUnit = m_model.createResource( "http://qudt.org/schema/qudt#ElectricFluxUnit" );
    
    public static final Resource ElectricityAndMagnetismUnit = m_model.createResource( "http://qudt.org/schema/qudt#ElectricityAndMagnetismUnit" );
    
    public static final Resource ElectrochemistryUnit = m_model.createResource( "http://qudt.org/schema/qudt#ElectrochemistryUnit" );
    
    public static final Resource EnergyAndWorkPerMassAmountOfSubstance = m_model.createResource( "http://qudt.org/schema/qudt#EnergyAndWorkPerMassAmountOfSubstance" );
    
    public static final Resource EnergyAndWorkUnit = m_model.createResource( "http://qudt.org/schema/qudt#EnergyAndWorkUnit" );
    
    public static final Resource EnergyDensityUnit = m_model.createResource( "http://qudt.org/schema/qudt#EnergyDensityUnit" );
    
    public static final Resource EnergyPerAreaUnit = m_model.createResource( "http://qudt.org/schema/qudt#EnergyPerAreaUnit" );
    
    public static final Resource EnergyPerElectricChargeUnit = m_model.createResource( "http://qudt.org/schema/qudt#EnergyPerElectricChargeUnit" );
    
    public static final Resource EnumeratedValue = m_model.createResource( "http://qudt.org/schema/qudt#EnumeratedValue" );
    
    public static final Resource Enumeration = m_model.createResource( "http://qudt.org/schema/qudt#Enumeration" );
    
    public static final Resource EventUnit = m_model.createResource( "http://qudt.org/schema/qudt#EventUnit" );
    
    public static final Resource ExposureUnit = m_model.createResource( "http://qudt.org/schema/qudt#ExposureUnit" );
    
    public static final Resource FinancialUnit = m_model.createResource( "http://qudt.org/schema/qudt#FinancialUnit" );
    
    public static final Resource ForcePerElectricChargeUnit = m_model.createResource( "http://qudt.org/schema/qudt#ForcePerElectricChargeUnit" );
    
    public static final Resource ForcePerLengthUnit = m_model.createResource( "http://qudt.org/schema/qudt#ForcePerLengthUnit" );
    
    public static final Resource ForceUnit = m_model.createResource( "http://qudt.org/schema/qudt#ForceUnit" );
    
    public static final Resource FrequencyUnit = m_model.createResource( "http://qudt.org/schema/qudt#FrequencyUnit" );
    
    public static final Resource GravitationalAttractionUnit = m_model.createResource( "http://qudt.org/schema/qudt#GravitationalAttractionUnit" );
    
    public static final Resource HeartRateUnit = m_model.createResource( "http://qudt.org/schema/qudt#HeartRateUnit" );
    
    public static final Resource HeatCapacityAndEntropyUnit = m_model.createResource( "http://qudt.org/schema/qudt#HeatCapacityAndEntropyUnit" );
    
    public static final Resource HeatFlowRateUnit = m_model.createResource( "http://qudt.org/schema/qudt#HeatFlowRateUnit" );
    
    public static final Resource HumanUnit = m_model.createResource( "http://qudt.org/schema/qudt#HumanUnit" );
    
    public static final Resource IlluminanceUnit = m_model.createResource( "http://qudt.org/schema/qudt#IlluminanceUnit" );
    
    public static final Resource InductanceUnit = m_model.createResource( "http://qudt.org/schema/qudt#InductanceUnit" );
    
    public static final Resource InformationEntropyUnit = m_model.createResource( "http://qudt.org/schema/qudt#InformationEntropyUnit" );
    
    public static final Resource InverseAmountOfSubstanceUnit = m_model.createResource( "http://qudt.org/schema/qudt#InverseAmountOfSubstanceUnit" );
    
    public static final Resource KinematicViscosityUnit = m_model.createResource( "http://qudt.org/schema/qudt#KinematicViscosityUnit" );
    
    public static final Resource LengthTemperatureTimeUnit = m_model.createResource( "http://qudt.org/schema/qudt#LengthTemperatureTimeUnit" );
    
    public static final Resource LengthTemperatureUnit = m_model.createResource( "http://qudt.org/schema/qudt#LengthTemperatureUnit" );
    
    public static final Resource LengthUnit = m_model.createResource( "http://qudt.org/schema/qudt#LengthUnit" );
    
    public static final Resource LinearAccelerationUnit = m_model.createResource( "http://qudt.org/schema/qudt#LinearAccelerationUnit" );
    
    public static final Resource LinearEnergyTransferUnit = m_model.createResource( "http://qudt.org/schema/qudt#LinearEnergyTransferUnit" );
    
    public static final Resource LinearMomentumUnit = m_model.createResource( "http://qudt.org/schema/qudt#LinearMomentumUnit" );
    
    public static final Resource LinearThermalExpansionUnit = m_model.createResource( "http://qudt.org/schema/qudt#LinearThermalExpansionUnit" );
    
    public static final Resource LinearVelocityUnit = m_model.createResource( "http://qudt.org/schema/qudt#LinearVelocityUnit" );
    
    public static final Resource LogarithmicUnit = m_model.createResource( "http://qudt.org/schema/qudt#LogarithmicUnit" );
    
    public static final Resource LuminanceUnit = m_model.createResource( "http://qudt.org/schema/qudt#LuminanceUnit" );
    
    public static final Resource LuminousEfficacyUnit = m_model.createResource( "http://qudt.org/schema/qudt#LuminousEfficacyUnit" );
    
    public static final Resource LuminousEnergyUnit = m_model.createResource( "http://qudt.org/schema/qudt#LuminousEnergyUnit" );
    
    public static final Resource LuminousFluxUnit = m_model.createResource( "http://qudt.org/schema/qudt#LuminousFluxUnit" );
    
    public static final Resource LuminousIntensityUnit = m_model.createResource( "http://qudt.org/schema/qudt#LuminousIntensityUnit" );
    
    public static final Resource MagneticFieldStrengthUnit = m_model.createResource( "http://qudt.org/schema/qudt#MagneticFieldStrengthUnit" );
    
    public static final Resource MagneticFluxDensityUnit = m_model.createResource( "http://qudt.org/schema/qudt#MagneticFluxDensityUnit" );
    
    public static final Resource MagneticFluxUnit = m_model.createResource( "http://qudt.org/schema/qudt#MagneticFluxUnit" );
    
    public static final Resource MagnetomotiveForceUnit = m_model.createResource( "http://qudt.org/schema/qudt#MagnetomotiveForceUnit" );
    
    public static final Resource MassAmountOfSubstanceTemperatureUnit = m_model.createResource( "http://qudt.org/schema/qudt#MassAmountOfSubstanceTemperatureUnit" );
    
    public static final Resource MassAmountOfSubstanceUnit = m_model.createResource( "http://qudt.org/schema/qudt#MassAmountOfSubstanceUnit" );
    
    public static final Resource MassPerAreaUnit = m_model.createResource( "http://qudt.org/schema/qudt#MassPerAreaUnit" );
    
    public static final Resource MassPerLengthUnit = m_model.createResource( "http://qudt.org/schema/qudt#MassPerLengthUnit" );
    
    public static final Resource MassPerTimeUnit = m_model.createResource( "http://qudt.org/schema/qudt#MassPerTimeUnit" );
    
    public static final Resource MassPerVolumeUnit = m_model.createResource( "http://qudt.org/schema/qudt#MassPerVolumeUnit" );
    
    public static final Resource MassTemperatureUnit = m_model.createResource( "http://qudt.org/schema/qudt#MassTemperatureUnit" );
    
    public static final Resource MassUnit = m_model.createResource( "http://qudt.org/schema/qudt#MassUnit" );
    
    public static final Resource MechanicsUnit = m_model.createResource( "http://qudt.org/schema/qudt#MechanicsUnit" );
    
    public static final Resource MicrobialFormationUnit = m_model.createResource( "http://qudt.org/schema/qudt#MicrobialFormationUnit" );
    
    public static final Resource MolalConcentrationUnit = m_model.createResource( "http://qudt.org/schema/qudt#MolalConcentrationUnit" );
    
    public static final Resource MolarConcentrationUnit = m_model.createResource( "http://qudt.org/schema/qudt#MolarConcentrationUnit" );
    
    public static final Resource MolarEnergyUnit = m_model.createResource( "http://qudt.org/schema/qudt#MolarEnergyUnit" );
    
    public static final Resource MolarHeatCapacityUnit = m_model.createResource( "http://qudt.org/schema/qudt#MolarHeatCapacityUnit" );
    
    public static final Resource MomentumUnit = m_model.createResource( "http://qudt.org/schema/qudt#MomentumUnit" );
    
    public static final Resource NonSIUnit = m_model.createResource( "http://qudt.org/schema/qudt#NonSIUnit" );
    
    public static final Resource NotUsedWithSIUnit = m_model.createResource( "http://qudt.org/schema/qudt#NotUsedWithSIUnit" );
    
    public static final Resource OpticsUnit = m_model.createResource( "http://qudt.org/schema/qudt#OpticsUnit" );
    
    public static final Resource PermeabilityUnit = m_model.createResource( "http://qudt.org/schema/qudt#PermeabilityUnit" );
    
    public static final Resource PermittivityUnit = m_model.createResource( "http://qudt.org/schema/qudt#PermittivityUnit" );
    
    public static final Resource PhotometryUnit = m_model.createResource( "http://qudt.org/schema/qudt#PhotometryUnit" );
    
    public static final Resource PhysicalUnit = m_model.createResource( "http://qudt.org/schema/qudt#PhysicalUnit" );
    
    public static final Resource PlaneAngleUnit = m_model.createResource( "http://qudt.org/schema/qudt#PlaneAngleUnit" );
    
    public static final Resource PowerPerAreaUnit = m_model.createResource( "http://qudt.org/schema/qudt#PowerPerAreaUnit" );
    
    public static final Resource PowerPerElectricChargeUnit = m_model.createResource( "http://qudt.org/schema/qudt#PowerPerElectricChargeUnit" );
    
    public static final Resource PowerUnit = m_model.createResource( "http://qudt.org/schema/qudt#PowerUnit" );
    
    public static final Resource PrefixUnit = m_model.createResource( "http://qudt.org/schema/qudt#PrefixUnit" );
    
    public static final Resource PressureOrStressRateUnit = m_model.createResource( "http://qudt.org/schema/qudt#PressureOrStressRateUnit" );
    
    public static final Resource PressureOrStressUnit = m_model.createResource( "http://qudt.org/schema/qudt#PressureOrStressUnit" );
    
    public static final Resource RF_PowerUnit = m_model.createResource( "http://qudt.org/schema/qudt#RF-PowerUnit" );
    
    public static final Resource RadianceUnit = m_model.createResource( "http://qudt.org/schema/qudt#RadianceUnit" );
    
    public static final Resource RadiantIntensityUnit = m_model.createResource( "http://qudt.org/schema/qudt#RadiantIntensityUnit" );
    
    public static final Resource RadiologyUnit = m_model.createResource( "http://qudt.org/schema/qudt#RadiologyUnit" );
    
    public static final Resource RadiometryUnit = m_model.createResource( "http://qudt.org/schema/qudt#RadiometryUnit" );
    
    public static final Resource RateOfReturnUnit = m_model.createResource( "http://qudt.org/schema/qudt#RateOfReturnUnit" );
    
    public static final Resource ResistanceUnit = m_model.createResource( "http://qudt.org/schema/qudt#ResistanceUnit" );
    
    public static final Resource ResourceUnit = m_model.createResource( "http://qudt.org/schema/qudt#ResourceUnit" );
    
    public static final Resource RespiratoryRateUnit = m_model.createResource( "http://qudt.org/schema/qudt#RespiratoryRateUnit" );
    
    public static final Resource SIBaseUnit = m_model.createResource( "http://qudt.org/schema/qudt#SIBaseUnit" );
    
    public static final Resource SIDerivedUnit = m_model.createResource( "http://qudt.org/schema/qudt#SIDerivedUnit" );
    
    public static final Resource SIUnit = m_model.createResource( "http://qudt.org/schema/qudt#SIUnit" );
    
    public static final Resource ScienceAndEngineeringUnit = m_model.createResource( "http://qudt.org/schema/qudt#ScienceAndEngineeringUnit" );
    
    public static final Resource SerumOrPlasmaLevelUnit = m_model.createResource( "http://qudt.org/schema/qudt#SerumOrPlasmaLevelUnit" );
    
    public static final Resource SignalDetectionThresholdUnit = m_model.createResource( "http://qudt.org/schema/qudt#SignalDetectionThresholdUnit" );
    
    public static final Resource SolidAngleUnit = m_model.createResource( "http://qudt.org/schema/qudt#SolidAngleUnit" );
    
    public static final Resource SpaceAndTimeUnit = m_model.createResource( "http://qudt.org/schema/qudt#SpaceAndTimeUnit" );
    
    public static final Resource SpecificEnergyUnit = m_model.createResource( "http://qudt.org/schema/qudt#SpecificEnergyUnit" );
    
    public static final Resource SpecificHeatCapacityUnit = m_model.createResource( "http://qudt.org/schema/qudt#SpecificHeatCapacityUnit" );
    
    public static final Resource SpecificHeatPressureUnit = m_model.createResource( "http://qudt.org/schema/qudt#SpecificHeatPressureUnit" );
    
    public static final Resource SpecificHeatVolumeUnit = m_model.createResource( "http://qudt.org/schema/qudt#SpecificHeatVolumeUnit" );
    
    public static final Resource SystemOfNaturalUnits = m_model.createResource( "http://qudt.org/schema/qudt#SystemOfNaturalUnits" );
    
    public static final Resource SystemOfUnits = m_model.createResource( "http://qudt.org/schema/qudt#SystemOfUnits" );
    
    public static final Resource TemperaturePerTimeUnit = m_model.createResource( "http://qudt.org/schema/qudt#TemperaturePerTimeUnit" );
    
    public static final Resource TemperatureUnit = m_model.createResource( "http://qudt.org/schema/qudt#TemperatureUnit" );
    
    public static final Resource ThermalConductivityUnit = m_model.createResource( "http://qudt.org/schema/qudt#ThermalConductivityUnit" );
    
    public static final Resource ThermalDiffusivityUnit = m_model.createResource( "http://qudt.org/schema/qudt#ThermalDiffusivityUnit" );
    
    public static final Resource ThermalEnergyLengthUnit = m_model.createResource( "http://qudt.org/schema/qudt#ThermalEnergyLengthUnit" );
    
    public static final Resource ThermalEnergyUnit = m_model.createResource( "http://qudt.org/schema/qudt#ThermalEnergyUnit" );
    
    public static final Resource ThermalExpansionUnit = m_model.createResource( "http://qudt.org/schema/qudt#ThermalExpansionUnit" );
    
    public static final Resource ThermalInsulanceUnit = m_model.createResource( "http://qudt.org/schema/qudt#ThermalInsulanceUnit" );
    
    public static final Resource ThermalResistanceUnit = m_model.createResource( "http://qudt.org/schema/qudt#ThermalResistanceUnit" );
    
    public static final Resource ThermalResistivityUnit = m_model.createResource( "http://qudt.org/schema/qudt#ThermalResistivityUnit" );
    
    public static final Resource ThermodynamicsUnit = m_model.createResource( "http://qudt.org/schema/qudt#ThermodynamicsUnit" );
    
    public static final Resource ThrustToMassRatioUnit = m_model.createResource( "http://qudt.org/schema/qudt#ThrustToMassRatioUnit" );
    
    public static final Resource TimeAreaUnit = m_model.createResource( "http://qudt.org/schema/qudt#TimeAreaUnit" );
    
    public static final Resource TimeSquaredUnit = m_model.createResource( "http://qudt.org/schema/qudt#TimeSquaredUnit" );
    
    public static final Resource TimeUnit = m_model.createResource( "http://qudt.org/schema/qudt#TimeUnit" );
    
    public static final Resource TurbidityUnit = m_model.createResource( "http://qudt.org/schema/qudt#TurbidityUnit" );
    
    public static final Resource Unit = m_model.createResource( "http://qudt.org/schema/qudt#Unit" );
    
    public static final Resource UsedWithSIUnit = m_model.createResource( "http://qudt.org/schema/qudt#UsedWithSIUnit" );
    
    public static final Resource VelocityUnit = m_model.createResource( "http://qudt.org/schema/qudt#VelocityUnit" );
    
    public static final Resource VideoFrameRateUnit = m_model.createResource( "http://qudt.org/schema/qudt#VideoFrameRateUnit" );
    
    public static final Resource VolumePerMassUnit = m_model.createResource( "http://qudt.org/schema/qudt#VolumePerMassUnit" );
    
    public static final Resource VolumePerTimeSquaredUnit = m_model.createResource( "http://qudt.org/schema/qudt#VolumePerTimeSquaredUnit" );
    
    public static final Resource VolumePerTimeUnit = m_model.createResource( "http://qudt.org/schema/qudt#VolumePerTimeUnit" );
    
    public static final Resource VolumeThermalExpansionUnit = m_model.createResource( "http://qudt.org/schema/qudt#VolumeThermalExpansionUnit" );
    
    public static final Resource VolumeUnit = m_model.createResource( "http://qudt.org/schema/qudt#VolumeUnit" );
    
}
